using System.Collections.Generic;

namespace Gilomx.CupheadBossRoulette
{
    internal sealed partial class ModLocalization
    {
        private static readonly ModText[] ApprovedLabelReviewIds =
        {
            ModText.ChallengeRgbShift,
            ModText.ChallengeUpsideDown,
            ModText.ChallengeHpOne,
            ModText.ChallengeInkRain,
            ModText.ChallengeHalfDamage,
            ModText.CreatorMenuRouletteOverlay,
            ModText.CreatorMenuStatus,
            ModText.CreatorMenuRetry,
            ModText.CreatorMenuPreview,
            ModText.CreatorMenuSize,
            ModText.CreatorMenuOrder,
            ModText.CreatorMenuAlignment,
            ModText.CreatorMenuOpacity,
            ModText.CreatorActionCopyUrl,
            ModText.CreatorActionBack,
            ModText.CreatorValueEnabled,
            ModText.CreatorValueDisabled,
            ModText.CreatorRetryKeep,
            ModText.CreatorRetryReappear,
            ModText.CreatorOrderIconsAbove,
            ModText.CreatorOrderTextAbove,
            ModText.CreatorAlignmentLeft,
            ModText.CreatorAlignmentCenter,
            ModText.CreatorAlignmentRight,
            ModText.CreatorFeedbackUrlCopied
        };

        private void ApplyApprovedLabelReviewTexts()
        {
            ApplyApprovedLabelReviewTexts(spanish,
                "Mamá escucho borroso",
                "Volteada de cabeza",
                "Una vida y te callas",
                "Lluvia de tinta",
                "Disparos rebajados",
                "Stream Overlay",
                "Estado",
                "Reintento",
                "Vista previa",
                "Tamaño",
                "Orden",
                "Alineación",
                "Opacidad",
                "Copiar URL",
                "VOLVER",
                "Activado",
                "Desactivado",
                "Mantener",
                "Reaparecer",
                "Iconos arriba",
                "Texto arriba",
                "Izquierda",
                "Centro",
                "Derecha",
                "URL copiada");

            ApplyApprovedLabelReviewTexts(spanishAmerica,
                "Mamá escucho borroso",
                "Volteada de cabeza",
                "Una vida y te callas",
                "Lluvia de tinta",
                "Disparos rebajados",
                "Stream Overlay",
                "Estado",
                "Reintento",
                "Vista previa",
                "Tamaño",
                "Orden",
                "Alineación",
                "Opacidad",
                "Copiar URL",
                "VOLVER",
                "Activado",
                "Desactivado",
                "Mantener",
                "Reaparecer",
                "Iconos arriba",
                "Texto arriba",
                "Izquierda",
                "Centro",
                "Derecha",
                "URL copiada");

            ApplyApprovedLabelReviewTexts(english,
                "Chromatic Chaos",
                "Upside Down",
                "1 HP. Deal With It.",
                "Ink Rain",
                "Damage -50%",
                "Stream Overlay",
                "Status",
                "Retry",
                "Preview",
                "Size",
                "Order",
                "Alignment",
                "Opacity",
                "Copy URL",
                "BACK",
                "Enabled",
                "Disabled",
                "Keep",
                "Reappear",
                "Icons Above",
                "Text Above",
                "Left",
                "Center",
                "Right",
                "URL Copied");

            ApplyApprovedLabelReviewTexts(french,
                "Chaos chromatique",
                "À l'envers",
                "1 PV. Fais avec.",
                "Pluie d'encre",
                "Dégâts -50 %",
                "Overlay de stream",
                "État",
                "Nouvel essai",
                "Aperçu",
                "Taille",
                "Ordre",
                "Alignement",
                "Opacité",
                "Copier l’URL",
                "RETOUR",
                "Activé",
                "Désactivé",
                "Conserver",
                "Réafficher",
                "Icônes en haut",
                "Texte en haut",
                "Gauche",
                "Centre",
                "Droite",
                "URL copiée");

            ApplyApprovedLabelReviewTexts(italian,
                "Caos cromatico",
                "Sottosopra",
                "1 HP. Fattene una ragione.",
                "Pioggia d'inchiostro",
                "Danni -50%",
                "Overlay streaming",
                "Stato",
                "Riprova",
                "Anteprima",
                "Dimensione",
                "Ordine",
                "Allineamento",
                "Opacità",
                "Copia URL",
                "INDIETRO",
                "Attivato",
                "Disattivato",
                "Mantieni",
                "Riappari",
                "Icone sopra",
                "Testo sopra",
                "Sinistra",
                "Centro",
                "Destra",
                "URL copiato");

            ApplyApprovedLabelReviewTexts(german,
                "Chromatisches Chaos",
                "Kopfüber",
                "1 KP. Find dich damit ab.",
                "Tintenregen",
                "Schaden -50 %",
                "Stream-Overlay",
                "Status",
                "Erneut",
                "Vorschau",
                "Größe",
                "Reihenfolge",
                "Ausrichtung",
                "Deckkraft",
                "URL kopieren",
                "ZURÜCK",
                "Aktiviert",
                "Deaktiviert",
                "Beibehalten",
                "Einblenden",
                "Symbole oben",
                "Text oben",
                "Links",
                "Mitte",
                "Rechts",
                "URL kopiert");

            ApplyApprovedLabelReviewTexts(korean,
                "색채 혼돈",
                "거꾸로",
                "HP 1. 알아서 버텨.",
                "잉크 비",
                "피해량 -50%",
                "스트림 오버레이",
                "상태",
                "재시도",
                "미리보기",
                "크기",
                "순서",
                "정렬",
                "불투명도",
                "URL 복사",
                "이전",
                "활성화",
                "비활성화",
                "유지",
                "다시 나타남",
                "아이콘이 위",
                "텍스트가 위",
                "왼쪽",
                "가운데",
                "오른쪽",
                "URL 복사됨");

            ApplyApprovedLabelReviewTexts(russian,
                "Хроматический хаос",
                "Вверх дном",
                "1 HP. Смирись.",
                "Чернильный дождь",
                "Урон -50%",
                "Оверлей стрима",
                "Статус",
                "Повтор",
                "Превью",
                "Размер",
                "Порядок",
                "Выравнивание",
                "Непрозрачность",
                "Копировать URL",
                "НАЗАД",
                "Включено",
                "Выключено",
                "Оставить",
                "Появиться",
                "Значки сверху",
                "Текст сверху",
                "Слева",
                "По центру",
                "Справа",
                "URL скопирован");

            ApplyApprovedLabelReviewTexts(polish,
                "Chromatyczny chaos",
                "Do góry nogami",
                "1 HP. Pogódź się z tym.",
                "Deszcz atramentu",
                "Obrażenia -50%",
                "Nakładka streamu",
                "Stan",
                "Ponownie",
                "Podgląd",
                "Rozmiar",
                "Kolejność",
                "Wyrównanie",
                "Krycie",
                "Kopiuj URL",
                "WSTECZ",
                "Włączone",
                "Wyłączone",
                "Zachowaj",
                "Pojaw się",
                "Ikony u góry",
                "Tekst u góry",
                "Do lewej",
                "Do środka",
                "Do prawej",
                "URL skopiowany");

            ApplyApprovedLabelReviewTexts(portugueseBrazil,
                "Caos cromático",
                "De cabeça para baixo",
                "1 HP. Se vira.",
                "Chuva de tinta",
                "Dano -50%",
                "Overlay da stream",
                "Status",
                "Nova tentativa",
                "Prévia",
                "Tamanho",
                "Ordem",
                "Alinhamento",
                "Opacidade",
                "Copiar URL",
                "VOLTAR",
                "Ativado",
                "Desativado",
                "Manter",
                "Reaparecer",
                "Ícones acima",
                "Texto acima",
                "Esquerda",
                "Centro",
                "Direita",
                "URL copiada");

            ApplyApprovedLabelReviewTexts(japanese,
                "色彩の混沌",
                "逆さま",
                "HP1。諦めろ。",
                "インクの雨",
                "ダメージ -50%",
                "配信オーバーレイ",
                "状態",
                "リトライ",
                "プレビュー",
                "サイズ",
                "順序",
                "配置",
                "不透明度",
                "URLをコピー",
                "戻る",
                "有効",
                "無効",
                "維持",
                "再表示",
                "アイコンを上に",
                "テキストを上に",
                "左",
                "中央",
                "右",
                "URLをコピーしました");

            ApplyApprovedLabelReviewTexts(simplifiedChinese,
                "色彩混沌",
                "上下颠倒",
                "1 HP。认了吧。",
                "墨水雨",
                "伤害 -50%",
                "直播叠加层",
                "状态",
                "重试",
                "预览",
                "大小",
                "顺序",
                "对齐",
                "不透明度",
                "复制 URL",
                "返回",
                "已启用",
                "已禁用",
                "保持",
                "重新出现",
                "图标在上",
                "文本在上",
                "左",
                "居中",
                "右",
                "URL 已复制");
        }

        private static void ApplyApprovedLabelReviewTexts(
            Dictionary<ModText, string> table, params string[] values)
        {
            if (values == null ||
                values.Length != ApprovedLabelReviewIds.Length)
                throw new System.ArgumentException(
                    "Approved label review table has an invalid length.");

            for (var i = 0; i < ApprovedLabelReviewIds.Length; i++)
                table[ApprovedLabelReviewIds[i]] = values[i];
        }
    }
}
