export const interactionCategories = ["help", "attack", "mini_boss", "challenge"] as const;
export type InteractionCategory = typeof interactionCategories[number];
export const interactionGroups = ["help", "light", "strong", "mini_boss", "challenge"] as const;
export type InteractionGroup = typeof interactionGroups[number];
export type InteractionCategoryFilter = "all" | InteractionGroup;

export const interactionItems = [
  {
    id: "help_extra_life",
    category: "help",
    group: "help",
    titleKey: "interactions.helps.extraLife",
    descriptionKey: "interactions.helps.extraLifeEffect",
    imageAltKey: "interactions.helps.extraLife",
    typeKey: "interactions.groups.help",
    image: "/assets/creator-tools/interactions/extra-life-heart.png",
  },
  {
    id: "challenge_half_damage",
    category: "challenge",
    group: "challenge",
    titleKey: "interactions.challenges.halfDamage",
    descriptionKey: "interactions.challenges.effect",
    imageAltKey: "interactions.challenges.halfDamage",
    typeKey: "interactions.groups.challenge",
    image: "/assets/creator-tools/modifiers/halfdamage_01.png",
  },
  {
    id: "challenge_no_ex",
    category: "challenge",
    group: "challenge",
    titleKey: "interactions.challenges.noEx",
    descriptionKey: "interactions.challenges.noExEffect",
    imageAltKey: "interactions.challenges.noEx",
    typeKey: "interactions.groups.challenge",
    image: "/assets/creator-tools/modifiers/noex_01.png",
  },
  {
    id: "challenge_no_dash",
    category: "challenge",
    group: "challenge",
    titleKey: "interactions.challenges.noDash",
    descriptionKey: "interactions.challenges.noDashEffect",
    imageAltKey: "interactions.challenges.noDash",
    typeKey: "interactions.groups.challenge",
    image: "/assets/creator-tools/modifiers/nodash_01.png",
  },
  {
    id: "challenge_stiff_mode",
    category: "challenge",
    group: "challenge",
    titleKey: "interactions.challenges.stiffMode",
    descriptionKey: "interactions.challenges.stiffModeEffect",
    imageAltKey: "interactions.challenges.stiffMode",
    typeKey: "interactions.groups.challenge",
    image: "/assets/creator-tools/modifiers/locked_01.png",
  },
  {
    id: "challenge_black_and_white",
    category: "challenge",
    group: "challenge",
    titleKey: "interactions.challenges.blackAndWhite",
    descriptionKey: "interactions.challenges.blackAndWhiteEffect",
    imageAltKey: "interactions.challenges.blackAndWhite",
    typeKey: "interactions.groups.challenge",
    image: "/assets/creator-tools/modifiers/blacknwhite_01.png",
  },
  {
    id: "challenge_no_bombs",
    category: "challenge",
    group: "challenge",
    titleKey: "interactions.challenges.noBombs",
    descriptionKey: "interactions.challenges.noBombsEffect",
    imageAltKey: "interactions.challenges.noBombs",
    typeKey: "interactions.challenges.planeOnly",
    image: "/assets/creator-tools/modifiers/nobombs_01.png",
  },
  {
    id: "challenge_no_peashooter",
    category: "challenge",
    group: "challenge",
    titleKey: "interactions.challenges.noPeashooter",
    descriptionKey: "interactions.challenges.noPeashooterEffect",
    imageAltKey: "interactions.challenges.noPeashooter",
    typeKey: "interactions.challenges.planeOnly",
    image: "/assets/creator-tools/modifiers/nopeashooter_01.png",
  },
  {
    id: "challenge_rgb_shift",
    category: "challenge",
    group: "challenge",
    titleKey: "interactions.challenges.rgbShift",
    descriptionKey: "interactions.challenges.rgbShiftEffect",
    imageAltKey: "interactions.challenges.rgbShift",
    typeKey: "interactions.groups.challenge",
    image: "/assets/creator-tools/modifiers/rgb_01.png",
  },
  {
    id: "challenge_upside_down",
    category: "challenge",
    group: "challenge",
    titleKey: "interactions.challenges.upsideDown",
    descriptionKey: "interactions.challenges.upsideDownEffect",
    imageAltKey: "interactions.challenges.upsideDown",
    typeKey: "interactions.groups.challenge",
    image: "/assets/creator-tools/modifiers/upside_down_01.png",
  },
  {
    id: "challenge_ink_rain",
    category: "challenge",
    group: "challenge",
    titleKey: "interactions.challenges.inkRain",
    descriptionKey: "interactions.challenges.inkRainEffect",
    imageAltKey: "interactions.challenges.inkRain",
    typeKey: "interactions.groups.challenge",
    image: "/assets/creator-tools/modifiers/inkrain_01.png",
  },
  {
    id: "challenge_mini_plane_only",
    category: "challenge",
    group: "challenge",
    titleKey: "interactions.challenges.miniPlaneOnly",
    descriptionKey: "interactions.challenges.miniPlaneOnlyEffect",
    imageAltKey: "interactions.challenges.miniPlaneOnly",
    typeKey: "interactions.challenges.planeOnly",
    image: "/assets/creator-tools/modifiers/mini_01.png",
  },
  {
    id: "challenge_hp_one",
    category: "challenge",
    group: "challenge",
    titleKey: "interactions.challenges.hpOne",
    descriptionKey: "interactions.challenges.hpOneEffect",
    imageAltKey: "interactions.challenges.hpOne",
    typeKey: "interactions.groups.challenge",
    image: "/assets/creator-tools/modifiers/hp1_01.png",
  },
  {
    id: "hilda_green_zeppelin",
    category: "attack",
    group: "strong",
    titleKey: "interactions.zeppelin.green.title",
    imageAltKey: "interactions.zeppelin.green.imageAlt",
    typeKey: "interactions.zeppelin.type",
    image: "/assets/creator-tools/interactions/green-zeppelin.png",
  },
  {
    id: "hilda_purple_zeppelin",
    category: "attack",
    group: "light",
    titleKey: "interactions.zeppelin.purple.title",
    imageAltKey: "interactions.zeppelin.purple.imageAlt",
    typeKey: "interactions.zeppelin.type",
    image: "/assets/creator-tools/interactions/purple-zeppelin.png",
  },
  {
    id: "rootpack_homing_carrot",
    category: "attack",
    group: "light",
    titleKey: "interactions.rootpack.homingCarrot.title",
    imageAltKey: "interactions.rootpack.homingCarrot.imageAlt",
    typeKey: "interactions.rootpack.type",
    image: "/assets/creator-tools/interactions/homing-carrot.png",
  },
  {
    id: "cagney_homing_plant",
    category: "attack",
    group: "light",
    titleKey: "interactions.cagney.homingPlant.title",
    imageAltKey: "interactions.cagney.homingPlant.imageAlt",
    typeKey: "interactions.cagney.type",
    image: "/assets/creator-tools/interactions/cagney-homing-plant.png",
  },
  {
    id: "frogs_firefly",
    category: "attack",
    group: "light",
    titleKey: "interactions.frogs.firefly.title",
    imageAltKey: "interactions.frogs.firefly.imageAlt",
    typeKey: "interactions.frogs.type",
    image: "/assets/creator-tools/interactions/frogs-firefly.png",
  },
  {
    id: "robot_homing_bomb",
    category: "attack",
    group: "strong",
    titleKey: "interactions.robot.homingBomb.title",
    imageAltKey: "interactions.robot.homingBomb.imageAlt",
    typeKey: "interactions.robot.type",
    image: "/assets/creator-tools/interactions/robot-homing-bomb.png",
  },
  {
    id: "baroness_head_toss",
    category: "attack",
    group: "strong",
    titleKey: "interactions.baroness.headToss.title",
    imageAltKey: "interactions.baroness.headToss.imageAlt",
    typeKey: "interactions.baroness.type",
    image: "/assets/creator-tools/interactions/baroness-head-toss.png",
  },
  {
    id: "dragon_fireballs",
    category: "attack",
    group: "strong",
    titleKey: "interactions.dragon.fireballs.title",
    imageAltKey: "interactions.dragon.fireballs.imageAlt",
    typeKey: "interactions.dragon.type",
    image: "/assets/creator-tools/interactions/dragon-fireballs.png",
  },
  {
    id: "train_bone_ring",
    category: "attack",
    group: "strong",
    titleKey: "interactions.train.boneRing.title",
    imageAltKey: "interactions.train.boneRing.imageAlt",
    typeKey: "interactions.train.type",
    image: "/assets/creator-tools/interactions/train-bone-ring.png",
  },
  {
    id: "devil_fire_circle",
    category: "attack",
    group: "strong",
    titleKey: "interactions.devil.fireCircle.title",
    imageAltKey: "interactions.devil.fireCircle.imageAlt",
    typeKey: "interactions.devil.type",
    image: "/assets/creator-tools/interactions/devil-fire-circle.png",
  },
  {
    id: "beppi_balloon_dog",
    category: "attack",
    group: "strong",
    titleKey: "interactions.beppi.balloonDog.title",
    imageAltKey: "interactions.beppi.balloonDog.imageAlt",
    typeKey: "interactions.beppi.type",
    image: "/assets/creator-tools/interactions/beppi-balloon-dog.png",
  },
  {
    id: "beppi_pink_balloon_dog",
    category: "attack",
    group: "light",
    titleKey: "interactions.beppi.pinkBalloonDog.title",
    imageAltKey: "interactions.beppi.pinkBalloonDog.imageAlt",
    typeKey: "interactions.beppi.type",
    image: "/assets/creator-tools/interactions/beppi-pink-balloon-dog.png",
  },
  {
    id: "baroness_cupcake",
    category: "mini_boss",
    group: "mini_boss",
    titleKey: "interactions.baroness.cupcake.title",
    imageAltKey: "interactions.baroness.cupcake.imageAlt",
    typeKey: "interactions.miniBoss.type",
    image: "/assets/creator-tools/interactions/baroness-cupcake.png",
  },
  {
    id: "baroness_gumball",
    category: "mini_boss",
    group: "mini_boss",
    titleKey: "interactions.baroness.gumball.title",
    imageAltKey: "interactions.baroness.gumball.imageAlt",
    typeKey: "interactions.miniBoss.type",
    image: "/assets/creator-tools/interactions/baroness-gumball.png",
  },
  {
    id: "baroness_waffle",
    category: "mini_boss",
    group: "mini_boss",
    titleKey: "interactions.baroness.waffle.title",
    imageAltKey: "interactions.baroness.waffle.imageAlt",
    typeKey: "interactions.miniBoss.type",
    image: "/assets/creator-tools/interactions/baroness-waffle.png",
  },
  {
    id: "baroness_candy_corn",
    category: "mini_boss",
    group: "mini_boss",
    titleKey: "interactions.baroness.candyCorn.title",
    imageAltKey: "interactions.baroness.candyCorn.imageAlt",
    typeKey: "interactions.miniBoss.type",
    image: "/assets/creator-tools/interactions/baroness-candy-corn.png",
  },
  {
    id: "baroness_jawbreaker",
    category: "mini_boss",
    group: "mini_boss",
    titleKey: "interactions.baroness.jawbreaker.title",
    imageAltKey: "interactions.baroness.jawbreaker.imageAlt",
    typeKey: "interactions.miniBoss.type",
    image: "/assets/creator-tools/interactions/baroness-jawbreaker.png",
  },
] as const;

export function interactionItemFor(item: string) {
  return interactionItems.find((catalogItem) => catalogItem.id === item);
}
